// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: tag_manager.proto

package rfidPb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RfidTagIndexController_BulkPushReturnInspectAgg_FullMethodName          = "/rfid_tag_manage.tag_service.RfidTagIndexController/BulkPushReturnInspectAgg"
	RfidTagIndexController_Create_FullMethodName                            = "/rfid_tag_manage.tag_service.RfidTagIndexController/Create"
	RfidTagIndexController_CreateRfidReasonEntities_FullMethodName          = "/rfid_tag_manage.tag_service.RfidTagIndexController/CreateRfidReasonEntities"
	RfidTagIndexController_CreateRfidReturnInspectConfig_FullMethodName     = "/rfid_tag_manage.tag_service.RfidTagIndexController/CreateRfidReturnInspectConfig"
	RfidTagIndexController_CreateRfidReturnInspectEntities_FullMethodName   = "/rfid_tag_manage.tag_service.RfidTagIndexController/CreateRfidReturnInspectEntities"
	RfidTagIndexController_Destroy_FullMethodName                           = "/rfid_tag_manage.tag_service.RfidTagIndexController/Destroy"
	RfidTagIndexController_DestroyReturnInspectAgg_FullMethodName           = "/rfid_tag_manage.tag_service.RfidTagIndexController/DestroyReturnInspectAgg"
	RfidTagIndexController_DestroyRfidReasonEntities_FullMethodName         = "/rfid_tag_manage.tag_service.RfidTagIndexController/DestroyRfidReasonEntities"
	RfidTagIndexController_DestroyRfidReturnInspectConfig_FullMethodName    = "/rfid_tag_manage.tag_service.RfidTagIndexController/DestroyRfidReturnInspectConfig"
	RfidTagIndexController_DestroyRfidReturnInspectEntities_FullMethodName  = "/rfid_tag_manage.tag_service.RfidTagIndexController/DestroyRfidReturnInspectEntities"
	RfidTagIndexController_InspectConfigOptions_FullMethodName              = "/rfid_tag_manage.tag_service.RfidTagIndexController/InspectConfigOptions"
	RfidTagIndexController_List_FullMethodName                              = "/rfid_tag_manage.tag_service.RfidTagIndexController/List"
	RfidTagIndexController_ListRfidReasonEntities_FullMethodName            = "/rfid_tag_manage.tag_service.RfidTagIndexController/ListRfidReasonEntities"
	RfidTagIndexController_ListRfidReturnInspectAgg_FullMethodName          = "/rfid_tag_manage.tag_service.RfidTagIndexController/ListRfidReturnInspectAgg"
	RfidTagIndexController_ListRfidReturnInspectConfig_FullMethodName       = "/rfid_tag_manage.tag_service.RfidTagIndexController/ListRfidReturnInspectConfig"
	RfidTagIndexController_ListRfidReturnInspectEntities_FullMethodName     = "/rfid_tag_manage.tag_service.RfidTagIndexController/ListRfidReturnInspectEntities"
	RfidTagIndexController_PartialUpdate_FullMethodName                     = "/rfid_tag_manage.tag_service.RfidTagIndexController/PartialUpdate"
	RfidTagIndexController_Retrieve_FullMethodName                          = "/rfid_tag_manage.tag_service.RfidTagIndexController/Retrieve"
	RfidTagIndexController_RetrieveReturnInspectAgg_FullMethodName          = "/rfid_tag_manage.tag_service.RfidTagIndexController/RetrieveReturnInspectAgg"
	RfidTagIndexController_RetrieveRfidReasonEntities_FullMethodName        = "/rfid_tag_manage.tag_service.RfidTagIndexController/RetrieveRfidReasonEntities"
	RfidTagIndexController_RetrieveRfidReturnInspectConfig_FullMethodName   = "/rfid_tag_manage.tag_service.RfidTagIndexController/RetrieveRfidReturnInspectConfig"
	RfidTagIndexController_RetrieveRfidReturnInspectEntities_FullMethodName = "/rfid_tag_manage.tag_service.RfidTagIndexController/RetrieveRfidReturnInspectEntities"
	RfidTagIndexController_RfidEpcSync_FullMethodName                       = "/rfid_tag_manage.tag_service.RfidTagIndexController/RfidEpcSync"
	RfidTagIndexController_RfidReturnInspectAggSync_FullMethodName          = "/rfid_tag_manage.tag_service.RfidTagIndexController/RfidReturnInspectAggSync"
	RfidTagIndexController_Update_FullMethodName                            = "/rfid_tag_manage.tag_service.RfidTagIndexController/Update"
	RfidTagIndexController_UpdateRfidReasonEntities_FullMethodName          = "/rfid_tag_manage.tag_service.RfidTagIndexController/UpdateRfidReasonEntities"
	RfidTagIndexController_UpdateRfidReturnInspectConfig_FullMethodName     = "/rfid_tag_manage.tag_service.RfidTagIndexController/UpdateRfidReturnInspectConfig"
	RfidTagIndexController_UpdateRfidReturnInspectEntities_FullMethodName   = "/rfid_tag_manage.tag_service.RfidTagIndexController/UpdateRfidReturnInspectEntities"
)

// RfidTagIndexControllerClient is the client API for RfidTagIndexController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RfidTagIndexControllerClient interface {
	BulkPushReturnInspectAgg(ctx context.Context, in *BulkPushReturnInspectAggRequest, opts ...grpc.CallOption) (*BulkPushReturnInspectAggResponse, error)
	Create(ctx context.Context, in *RfidTagIndexRequest, opts ...grpc.CallOption) (*RfidTagIndexResponse, error)
	CreateRfidReasonEntities(ctx context.Context, in *RfidReasonEntitiesCreateRequest, opts ...grpc.CallOption) (*RfidReasonEntitiesResponse, error)
	CreateRfidReturnInspectConfig(ctx context.Context, in *RfidReturnInspectConfigCreateRequest, opts ...grpc.CallOption) (*RfidReturnInspectConfigResponse, error)
	CreateRfidReturnInspectEntities(ctx context.Context, in *RfidReturnInspectEntitiesCreateRequest, opts ...grpc.CallOption) (*RfidReturnInspectEntitiesResponse, error)
	Destroy(ctx context.Context, in *RfidTagIndexDestroyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DestroyReturnInspectAgg(ctx context.Context, in *DestroyReturnInspectAggRequest, opts ...grpc.CallOption) (*DestroyReturnInspectAggResponse, error)
	DestroyRfidReasonEntities(ctx context.Context, in *RfidReasonEntitiesDestroyRequest, opts ...grpc.CallOption) (*RfidTagIndexDestroyRfidReasonEntitiesResponse, error)
	DestroyRfidReturnInspectConfig(ctx context.Context, in *RfidReturnInspectConfigDestroyRequest, opts ...grpc.CallOption) (*RfidTagIndexDestroyRfidReturnInspectConfigResponse, error)
	DestroyRfidReturnInspectEntities(ctx context.Context, in *RfidReturnInspectEntitiesDestroyRequest, opts ...grpc.CallOption) (*RfidTagIndexDestroyRfidReturnInspectEntitiesResponse, error)
	InspectConfigOptions(ctx context.Context, in *InspectConfigOptionsRequest, opts ...grpc.CallOption) (*InspectConfigOptionsResponse, error)
	List(ctx context.Context, in *RfidTagIndexListRequest, opts ...grpc.CallOption) (*RfidTagIndexListResponse, error)
	ListRfidReasonEntities(ctx context.Context, in *RfidReasonEntitiesListRequest, opts ...grpc.CallOption) (*RfidReasonEntitiesListResponse, error)
	ListRfidReturnInspectAgg(ctx context.Context, in *RfidReturnInspectAggListRequest, opts ...grpc.CallOption) (*RfidReturnInspectAggListResponse, error)
	ListRfidReturnInspectConfig(ctx context.Context, in *RfidReturnInspectConfigListRequest, opts ...grpc.CallOption) (*RfidReturnInspectConfigListResponse, error)
	ListRfidReturnInspectEntities(ctx context.Context, in *RfidReturnInspectEntitiesListRequest, opts ...grpc.CallOption) (*RfidReturnInspectEntitiesListResponse, error)
	PartialUpdate(ctx context.Context, in *RfidTagIndexPartialUpdateRequest, opts ...grpc.CallOption) (*RfidTagIndexResponse, error)
	Retrieve(ctx context.Context, in *RfidTagIndexRetrieveRequest, opts ...grpc.CallOption) (*RfidTagIndexResponse, error)
	RetrieveReturnInspectAgg(ctx context.Context, in *RetrieveReturnInspectAggRequest, opts ...grpc.CallOption) (*RfidReturnInspectAggResponse, error)
	RetrieveRfidReasonEntities(ctx context.Context, in *RfidReasonEntitiesRetrieveRequest, opts ...grpc.CallOption) (*RfidReasonEntitiesResponse, error)
	RetrieveRfidReturnInspectConfig(ctx context.Context, in *RfidReturnInspectConfigRetrieveRequest, opts ...grpc.CallOption) (*RfidReturnInspectConfigResponse, error)
	RetrieveRfidReturnInspectEntities(ctx context.Context, in *RfidReturnInspectEntitiesRetrieveRequest, opts ...grpc.CallOption) (*RfidReturnInspectEntitiesResponse, error)
	RfidEpcSync(ctx context.Context, in *EpcSyncRequest, opts ...grpc.CallOption) (*EpcSyncResponse, error)
	RfidReturnInspectAggSync(ctx context.Context, in *RfidReturnInspectAggSyncRequest, opts ...grpc.CallOption) (*RfidReturnInspectAggSyncResponse, error)
	Update(ctx context.Context, in *RfidTagIndexRequest, opts ...grpc.CallOption) (*RfidTagIndexResponse, error)
	UpdateRfidReasonEntities(ctx context.Context, in *RfidReasonEntitiesUpdateRequest, opts ...grpc.CallOption) (*RfidReasonEntitiesResponse, error)
	UpdateRfidReturnInspectConfig(ctx context.Context, in *RfidReturnInspectConfigUpdateRequest, opts ...grpc.CallOption) (*RfidReturnInspectConfigResponse, error)
	UpdateRfidReturnInspectEntities(ctx context.Context, in *RfidReturnInspectEntitiesUpdateRequest, opts ...grpc.CallOption) (*RfidReturnInspectEntitiesResponse, error)
}

type rfidTagIndexControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewRfidTagIndexControllerClient(cc grpc.ClientConnInterface) RfidTagIndexControllerClient {
	return &rfidTagIndexControllerClient{cc}
}

func (c *rfidTagIndexControllerClient) BulkPushReturnInspectAgg(ctx context.Context, in *BulkPushReturnInspectAggRequest, opts ...grpc.CallOption) (*BulkPushReturnInspectAggResponse, error) {
	out := new(BulkPushReturnInspectAggResponse)
	err := c.cc.Invoke(ctx, RfidTagIndexController_BulkPushReturnInspectAgg_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rfidTagIndexControllerClient) Create(ctx context.Context, in *RfidTagIndexRequest, opts ...grpc.CallOption) (*RfidTagIndexResponse, error) {
	out := new(RfidTagIndexResponse)
	err := c.cc.Invoke(ctx, RfidTagIndexController_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rfidTagIndexControllerClient) CreateRfidReasonEntities(ctx context.Context, in *RfidReasonEntitiesCreateRequest, opts ...grpc.CallOption) (*RfidReasonEntitiesResponse, error) {
	out := new(RfidReasonEntitiesResponse)
	err := c.cc.Invoke(ctx, RfidTagIndexController_CreateRfidReasonEntities_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rfidTagIndexControllerClient) CreateRfidReturnInspectConfig(ctx context.Context, in *RfidReturnInspectConfigCreateRequest, opts ...grpc.CallOption) (*RfidReturnInspectConfigResponse, error) {
	out := new(RfidReturnInspectConfigResponse)
	err := c.cc.Invoke(ctx, RfidTagIndexController_CreateRfidReturnInspectConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rfidTagIndexControllerClient) CreateRfidReturnInspectEntities(ctx context.Context, in *RfidReturnInspectEntitiesCreateRequest, opts ...grpc.CallOption) (*RfidReturnInspectEntitiesResponse, error) {
	out := new(RfidReturnInspectEntitiesResponse)
	err := c.cc.Invoke(ctx, RfidTagIndexController_CreateRfidReturnInspectEntities_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rfidTagIndexControllerClient) Destroy(ctx context.Context, in *RfidTagIndexDestroyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RfidTagIndexController_Destroy_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rfidTagIndexControllerClient) DestroyReturnInspectAgg(ctx context.Context, in *DestroyReturnInspectAggRequest, opts ...grpc.CallOption) (*DestroyReturnInspectAggResponse, error) {
	out := new(DestroyReturnInspectAggResponse)
	err := c.cc.Invoke(ctx, RfidTagIndexController_DestroyReturnInspectAgg_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rfidTagIndexControllerClient) DestroyRfidReasonEntities(ctx context.Context, in *RfidReasonEntitiesDestroyRequest, opts ...grpc.CallOption) (*RfidTagIndexDestroyRfidReasonEntitiesResponse, error) {
	out := new(RfidTagIndexDestroyRfidReasonEntitiesResponse)
	err := c.cc.Invoke(ctx, RfidTagIndexController_DestroyRfidReasonEntities_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rfidTagIndexControllerClient) DestroyRfidReturnInspectConfig(ctx context.Context, in *RfidReturnInspectConfigDestroyRequest, opts ...grpc.CallOption) (*RfidTagIndexDestroyRfidReturnInspectConfigResponse, error) {
	out := new(RfidTagIndexDestroyRfidReturnInspectConfigResponse)
	err := c.cc.Invoke(ctx, RfidTagIndexController_DestroyRfidReturnInspectConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rfidTagIndexControllerClient) DestroyRfidReturnInspectEntities(ctx context.Context, in *RfidReturnInspectEntitiesDestroyRequest, opts ...grpc.CallOption) (*RfidTagIndexDestroyRfidReturnInspectEntitiesResponse, error) {
	out := new(RfidTagIndexDestroyRfidReturnInspectEntitiesResponse)
	err := c.cc.Invoke(ctx, RfidTagIndexController_DestroyRfidReturnInspectEntities_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rfidTagIndexControllerClient) InspectConfigOptions(ctx context.Context, in *InspectConfigOptionsRequest, opts ...grpc.CallOption) (*InspectConfigOptionsResponse, error) {
	out := new(InspectConfigOptionsResponse)
	err := c.cc.Invoke(ctx, RfidTagIndexController_InspectConfigOptions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rfidTagIndexControllerClient) List(ctx context.Context, in *RfidTagIndexListRequest, opts ...grpc.CallOption) (*RfidTagIndexListResponse, error) {
	out := new(RfidTagIndexListResponse)
	err := c.cc.Invoke(ctx, RfidTagIndexController_List_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rfidTagIndexControllerClient) ListRfidReasonEntities(ctx context.Context, in *RfidReasonEntitiesListRequest, opts ...grpc.CallOption) (*RfidReasonEntitiesListResponse, error) {
	out := new(RfidReasonEntitiesListResponse)
	err := c.cc.Invoke(ctx, RfidTagIndexController_ListRfidReasonEntities_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rfidTagIndexControllerClient) ListRfidReturnInspectAgg(ctx context.Context, in *RfidReturnInspectAggListRequest, opts ...grpc.CallOption) (*RfidReturnInspectAggListResponse, error) {
	out := new(RfidReturnInspectAggListResponse)
	err := c.cc.Invoke(ctx, RfidTagIndexController_ListRfidReturnInspectAgg_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rfidTagIndexControllerClient) ListRfidReturnInspectConfig(ctx context.Context, in *RfidReturnInspectConfigListRequest, opts ...grpc.CallOption) (*RfidReturnInspectConfigListResponse, error) {
	out := new(RfidReturnInspectConfigListResponse)
	err := c.cc.Invoke(ctx, RfidTagIndexController_ListRfidReturnInspectConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rfidTagIndexControllerClient) ListRfidReturnInspectEntities(ctx context.Context, in *RfidReturnInspectEntitiesListRequest, opts ...grpc.CallOption) (*RfidReturnInspectEntitiesListResponse, error) {
	out := new(RfidReturnInspectEntitiesListResponse)
	err := c.cc.Invoke(ctx, RfidTagIndexController_ListRfidReturnInspectEntities_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rfidTagIndexControllerClient) PartialUpdate(ctx context.Context, in *RfidTagIndexPartialUpdateRequest, opts ...grpc.CallOption) (*RfidTagIndexResponse, error) {
	out := new(RfidTagIndexResponse)
	err := c.cc.Invoke(ctx, RfidTagIndexController_PartialUpdate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rfidTagIndexControllerClient) Retrieve(ctx context.Context, in *RfidTagIndexRetrieveRequest, opts ...grpc.CallOption) (*RfidTagIndexResponse, error) {
	out := new(RfidTagIndexResponse)
	err := c.cc.Invoke(ctx, RfidTagIndexController_Retrieve_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rfidTagIndexControllerClient) RetrieveReturnInspectAgg(ctx context.Context, in *RetrieveReturnInspectAggRequest, opts ...grpc.CallOption) (*RfidReturnInspectAggResponse, error) {
	out := new(RfidReturnInspectAggResponse)
	err := c.cc.Invoke(ctx, RfidTagIndexController_RetrieveReturnInspectAgg_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rfidTagIndexControllerClient) RetrieveRfidReasonEntities(ctx context.Context, in *RfidReasonEntitiesRetrieveRequest, opts ...grpc.CallOption) (*RfidReasonEntitiesResponse, error) {
	out := new(RfidReasonEntitiesResponse)
	err := c.cc.Invoke(ctx, RfidTagIndexController_RetrieveRfidReasonEntities_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rfidTagIndexControllerClient) RetrieveRfidReturnInspectConfig(ctx context.Context, in *RfidReturnInspectConfigRetrieveRequest, opts ...grpc.CallOption) (*RfidReturnInspectConfigResponse, error) {
	out := new(RfidReturnInspectConfigResponse)
	err := c.cc.Invoke(ctx, RfidTagIndexController_RetrieveRfidReturnInspectConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rfidTagIndexControllerClient) RetrieveRfidReturnInspectEntities(ctx context.Context, in *RfidReturnInspectEntitiesRetrieveRequest, opts ...grpc.CallOption) (*RfidReturnInspectEntitiesResponse, error) {
	out := new(RfidReturnInspectEntitiesResponse)
	err := c.cc.Invoke(ctx, RfidTagIndexController_RetrieveRfidReturnInspectEntities_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rfidTagIndexControllerClient) RfidEpcSync(ctx context.Context, in *EpcSyncRequest, opts ...grpc.CallOption) (*EpcSyncResponse, error) {
	out := new(EpcSyncResponse)
	err := c.cc.Invoke(ctx, RfidTagIndexController_RfidEpcSync_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rfidTagIndexControllerClient) RfidReturnInspectAggSync(ctx context.Context, in *RfidReturnInspectAggSyncRequest, opts ...grpc.CallOption) (*RfidReturnInspectAggSyncResponse, error) {
	out := new(RfidReturnInspectAggSyncResponse)
	err := c.cc.Invoke(ctx, RfidTagIndexController_RfidReturnInspectAggSync_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rfidTagIndexControllerClient) Update(ctx context.Context, in *RfidTagIndexRequest, opts ...grpc.CallOption) (*RfidTagIndexResponse, error) {
	out := new(RfidTagIndexResponse)
	err := c.cc.Invoke(ctx, RfidTagIndexController_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rfidTagIndexControllerClient) UpdateRfidReasonEntities(ctx context.Context, in *RfidReasonEntitiesUpdateRequest, opts ...grpc.CallOption) (*RfidReasonEntitiesResponse, error) {
	out := new(RfidReasonEntitiesResponse)
	err := c.cc.Invoke(ctx, RfidTagIndexController_UpdateRfidReasonEntities_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rfidTagIndexControllerClient) UpdateRfidReturnInspectConfig(ctx context.Context, in *RfidReturnInspectConfigUpdateRequest, opts ...grpc.CallOption) (*RfidReturnInspectConfigResponse, error) {
	out := new(RfidReturnInspectConfigResponse)
	err := c.cc.Invoke(ctx, RfidTagIndexController_UpdateRfidReturnInspectConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rfidTagIndexControllerClient) UpdateRfidReturnInspectEntities(ctx context.Context, in *RfidReturnInspectEntitiesUpdateRequest, opts ...grpc.CallOption) (*RfidReturnInspectEntitiesResponse, error) {
	out := new(RfidReturnInspectEntitiesResponse)
	err := c.cc.Invoke(ctx, RfidTagIndexController_UpdateRfidReturnInspectEntities_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RfidTagIndexControllerServer is the server API for RfidTagIndexController service.
// All implementations must embed UnimplementedRfidTagIndexControllerServer
// for forward compatibility
type RfidTagIndexControllerServer interface {
	BulkPushReturnInspectAgg(context.Context, *BulkPushReturnInspectAggRequest) (*BulkPushReturnInspectAggResponse, error)
	Create(context.Context, *RfidTagIndexRequest) (*RfidTagIndexResponse, error)
	CreateRfidReasonEntities(context.Context, *RfidReasonEntitiesCreateRequest) (*RfidReasonEntitiesResponse, error)
	CreateRfidReturnInspectConfig(context.Context, *RfidReturnInspectConfigCreateRequest) (*RfidReturnInspectConfigResponse, error)
	CreateRfidReturnInspectEntities(context.Context, *RfidReturnInspectEntitiesCreateRequest) (*RfidReturnInspectEntitiesResponse, error)
	Destroy(context.Context, *RfidTagIndexDestroyRequest) (*emptypb.Empty, error)
	DestroyReturnInspectAgg(context.Context, *DestroyReturnInspectAggRequest) (*DestroyReturnInspectAggResponse, error)
	DestroyRfidReasonEntities(context.Context, *RfidReasonEntitiesDestroyRequest) (*RfidTagIndexDestroyRfidReasonEntitiesResponse, error)
	DestroyRfidReturnInspectConfig(context.Context, *RfidReturnInspectConfigDestroyRequest) (*RfidTagIndexDestroyRfidReturnInspectConfigResponse, error)
	DestroyRfidReturnInspectEntities(context.Context, *RfidReturnInspectEntitiesDestroyRequest) (*RfidTagIndexDestroyRfidReturnInspectEntitiesResponse, error)
	InspectConfigOptions(context.Context, *InspectConfigOptionsRequest) (*InspectConfigOptionsResponse, error)
	List(context.Context, *RfidTagIndexListRequest) (*RfidTagIndexListResponse, error)
	ListRfidReasonEntities(context.Context, *RfidReasonEntitiesListRequest) (*RfidReasonEntitiesListResponse, error)
	ListRfidReturnInspectAgg(context.Context, *RfidReturnInspectAggListRequest) (*RfidReturnInspectAggListResponse, error)
	ListRfidReturnInspectConfig(context.Context, *RfidReturnInspectConfigListRequest) (*RfidReturnInspectConfigListResponse, error)
	ListRfidReturnInspectEntities(context.Context, *RfidReturnInspectEntitiesListRequest) (*RfidReturnInspectEntitiesListResponse, error)
	PartialUpdate(context.Context, *RfidTagIndexPartialUpdateRequest) (*RfidTagIndexResponse, error)
	Retrieve(context.Context, *RfidTagIndexRetrieveRequest) (*RfidTagIndexResponse, error)
	RetrieveReturnInspectAgg(context.Context, *RetrieveReturnInspectAggRequest) (*RfidReturnInspectAggResponse, error)
	RetrieveRfidReasonEntities(context.Context, *RfidReasonEntitiesRetrieveRequest) (*RfidReasonEntitiesResponse, error)
	RetrieveRfidReturnInspectConfig(context.Context, *RfidReturnInspectConfigRetrieveRequest) (*RfidReturnInspectConfigResponse, error)
	RetrieveRfidReturnInspectEntities(context.Context, *RfidReturnInspectEntitiesRetrieveRequest) (*RfidReturnInspectEntitiesResponse, error)
	RfidEpcSync(context.Context, *EpcSyncRequest) (*EpcSyncResponse, error)
	RfidReturnInspectAggSync(context.Context, *RfidReturnInspectAggSyncRequest) (*RfidReturnInspectAggSyncResponse, error)
	Update(context.Context, *RfidTagIndexRequest) (*RfidTagIndexResponse, error)
	UpdateRfidReasonEntities(context.Context, *RfidReasonEntitiesUpdateRequest) (*RfidReasonEntitiesResponse, error)
	UpdateRfidReturnInspectConfig(context.Context, *RfidReturnInspectConfigUpdateRequest) (*RfidReturnInspectConfigResponse, error)
	UpdateRfidReturnInspectEntities(context.Context, *RfidReturnInspectEntitiesUpdateRequest) (*RfidReturnInspectEntitiesResponse, error)
	mustEmbedUnimplementedRfidTagIndexControllerServer()
}

// UnimplementedRfidTagIndexControllerServer must be embedded to have forward compatible implementations.
type UnimplementedRfidTagIndexControllerServer struct {
}

func (UnimplementedRfidTagIndexControllerServer) BulkPushReturnInspectAgg(context.Context, *BulkPushReturnInspectAggRequest) (*BulkPushReturnInspectAggResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BulkPushReturnInspectAgg not implemented")
}
func (UnimplementedRfidTagIndexControllerServer) Create(context.Context, *RfidTagIndexRequest) (*RfidTagIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedRfidTagIndexControllerServer) CreateRfidReasonEntities(context.Context, *RfidReasonEntitiesCreateRequest) (*RfidReasonEntitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRfidReasonEntities not implemented")
}
func (UnimplementedRfidTagIndexControllerServer) CreateRfidReturnInspectConfig(context.Context, *RfidReturnInspectConfigCreateRequest) (*RfidReturnInspectConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRfidReturnInspectConfig not implemented")
}
func (UnimplementedRfidTagIndexControllerServer) CreateRfidReturnInspectEntities(context.Context, *RfidReturnInspectEntitiesCreateRequest) (*RfidReturnInspectEntitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRfidReturnInspectEntities not implemented")
}
func (UnimplementedRfidTagIndexControllerServer) Destroy(context.Context, *RfidTagIndexDestroyRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Destroy not implemented")
}
func (UnimplementedRfidTagIndexControllerServer) DestroyReturnInspectAgg(context.Context, *DestroyReturnInspectAggRequest) (*DestroyReturnInspectAggResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestroyReturnInspectAgg not implemented")
}
func (UnimplementedRfidTagIndexControllerServer) DestroyRfidReasonEntities(context.Context, *RfidReasonEntitiesDestroyRequest) (*RfidTagIndexDestroyRfidReasonEntitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestroyRfidReasonEntities not implemented")
}
func (UnimplementedRfidTagIndexControllerServer) DestroyRfidReturnInspectConfig(context.Context, *RfidReturnInspectConfigDestroyRequest) (*RfidTagIndexDestroyRfidReturnInspectConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestroyRfidReturnInspectConfig not implemented")
}
func (UnimplementedRfidTagIndexControllerServer) DestroyRfidReturnInspectEntities(context.Context, *RfidReturnInspectEntitiesDestroyRequest) (*RfidTagIndexDestroyRfidReturnInspectEntitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestroyRfidReturnInspectEntities not implemented")
}
func (UnimplementedRfidTagIndexControllerServer) InspectConfigOptions(context.Context, *InspectConfigOptionsRequest) (*InspectConfigOptionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InspectConfigOptions not implemented")
}
func (UnimplementedRfidTagIndexControllerServer) List(context.Context, *RfidTagIndexListRequest) (*RfidTagIndexListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedRfidTagIndexControllerServer) ListRfidReasonEntities(context.Context, *RfidReasonEntitiesListRequest) (*RfidReasonEntitiesListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRfidReasonEntities not implemented")
}
func (UnimplementedRfidTagIndexControllerServer) ListRfidReturnInspectAgg(context.Context, *RfidReturnInspectAggListRequest) (*RfidReturnInspectAggListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRfidReturnInspectAgg not implemented")
}
func (UnimplementedRfidTagIndexControllerServer) ListRfidReturnInspectConfig(context.Context, *RfidReturnInspectConfigListRequest) (*RfidReturnInspectConfigListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRfidReturnInspectConfig not implemented")
}
func (UnimplementedRfidTagIndexControllerServer) ListRfidReturnInspectEntities(context.Context, *RfidReturnInspectEntitiesListRequest) (*RfidReturnInspectEntitiesListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRfidReturnInspectEntities not implemented")
}
func (UnimplementedRfidTagIndexControllerServer) PartialUpdate(context.Context, *RfidTagIndexPartialUpdateRequest) (*RfidTagIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PartialUpdate not implemented")
}
func (UnimplementedRfidTagIndexControllerServer) Retrieve(context.Context, *RfidTagIndexRetrieveRequest) (*RfidTagIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Retrieve not implemented")
}
func (UnimplementedRfidTagIndexControllerServer) RetrieveReturnInspectAgg(context.Context, *RetrieveReturnInspectAggRequest) (*RfidReturnInspectAggResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveReturnInspectAgg not implemented")
}
func (UnimplementedRfidTagIndexControllerServer) RetrieveRfidReasonEntities(context.Context, *RfidReasonEntitiesRetrieveRequest) (*RfidReasonEntitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveRfidReasonEntities not implemented")
}
func (UnimplementedRfidTagIndexControllerServer) RetrieveRfidReturnInspectConfig(context.Context, *RfidReturnInspectConfigRetrieveRequest) (*RfidReturnInspectConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveRfidReturnInspectConfig not implemented")
}
func (UnimplementedRfidTagIndexControllerServer) RetrieveRfidReturnInspectEntities(context.Context, *RfidReturnInspectEntitiesRetrieveRequest) (*RfidReturnInspectEntitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveRfidReturnInspectEntities not implemented")
}
func (UnimplementedRfidTagIndexControllerServer) RfidEpcSync(context.Context, *EpcSyncRequest) (*EpcSyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RfidEpcSync not implemented")
}
func (UnimplementedRfidTagIndexControllerServer) RfidReturnInspectAggSync(context.Context, *RfidReturnInspectAggSyncRequest) (*RfidReturnInspectAggSyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RfidReturnInspectAggSync not implemented")
}
func (UnimplementedRfidTagIndexControllerServer) Update(context.Context, *RfidTagIndexRequest) (*RfidTagIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedRfidTagIndexControllerServer) UpdateRfidReasonEntities(context.Context, *RfidReasonEntitiesUpdateRequest) (*RfidReasonEntitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRfidReasonEntities not implemented")
}
func (UnimplementedRfidTagIndexControllerServer) UpdateRfidReturnInspectConfig(context.Context, *RfidReturnInspectConfigUpdateRequest) (*RfidReturnInspectConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRfidReturnInspectConfig not implemented")
}
func (UnimplementedRfidTagIndexControllerServer) UpdateRfidReturnInspectEntities(context.Context, *RfidReturnInspectEntitiesUpdateRequest) (*RfidReturnInspectEntitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRfidReturnInspectEntities not implemented")
}
func (UnimplementedRfidTagIndexControllerServer) mustEmbedUnimplementedRfidTagIndexControllerServer() {
}

// UnsafeRfidTagIndexControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RfidTagIndexControllerServer will
// result in compilation errors.
type UnsafeRfidTagIndexControllerServer interface {
	mustEmbedUnimplementedRfidTagIndexControllerServer()
}

func RegisterRfidTagIndexControllerServer(s grpc.ServiceRegistrar, srv RfidTagIndexControllerServer) {
	s.RegisterService(&RfidTagIndexController_ServiceDesc, srv)
}

func _RfidTagIndexController_BulkPushReturnInspectAgg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkPushReturnInspectAggRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RfidTagIndexControllerServer).BulkPushReturnInspectAgg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RfidTagIndexController_BulkPushReturnInspectAgg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RfidTagIndexControllerServer).BulkPushReturnInspectAgg(ctx, req.(*BulkPushReturnInspectAggRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RfidTagIndexController_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RfidTagIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RfidTagIndexControllerServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RfidTagIndexController_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RfidTagIndexControllerServer).Create(ctx, req.(*RfidTagIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RfidTagIndexController_CreateRfidReasonEntities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RfidReasonEntitiesCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RfidTagIndexControllerServer).CreateRfidReasonEntities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RfidTagIndexController_CreateRfidReasonEntities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RfidTagIndexControllerServer).CreateRfidReasonEntities(ctx, req.(*RfidReasonEntitiesCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RfidTagIndexController_CreateRfidReturnInspectConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RfidReturnInspectConfigCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RfidTagIndexControllerServer).CreateRfidReturnInspectConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RfidTagIndexController_CreateRfidReturnInspectConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RfidTagIndexControllerServer).CreateRfidReturnInspectConfig(ctx, req.(*RfidReturnInspectConfigCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RfidTagIndexController_CreateRfidReturnInspectEntities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RfidReturnInspectEntitiesCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RfidTagIndexControllerServer).CreateRfidReturnInspectEntities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RfidTagIndexController_CreateRfidReturnInspectEntities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RfidTagIndexControllerServer).CreateRfidReturnInspectEntities(ctx, req.(*RfidReturnInspectEntitiesCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RfidTagIndexController_Destroy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RfidTagIndexDestroyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RfidTagIndexControllerServer).Destroy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RfidTagIndexController_Destroy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RfidTagIndexControllerServer).Destroy(ctx, req.(*RfidTagIndexDestroyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RfidTagIndexController_DestroyReturnInspectAgg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyReturnInspectAggRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RfidTagIndexControllerServer).DestroyReturnInspectAgg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RfidTagIndexController_DestroyReturnInspectAgg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RfidTagIndexControllerServer).DestroyReturnInspectAgg(ctx, req.(*DestroyReturnInspectAggRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RfidTagIndexController_DestroyRfidReasonEntities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RfidReasonEntitiesDestroyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RfidTagIndexControllerServer).DestroyRfidReasonEntities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RfidTagIndexController_DestroyRfidReasonEntities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RfidTagIndexControllerServer).DestroyRfidReasonEntities(ctx, req.(*RfidReasonEntitiesDestroyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RfidTagIndexController_DestroyRfidReturnInspectConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RfidReturnInspectConfigDestroyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RfidTagIndexControllerServer).DestroyRfidReturnInspectConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RfidTagIndexController_DestroyRfidReturnInspectConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RfidTagIndexControllerServer).DestroyRfidReturnInspectConfig(ctx, req.(*RfidReturnInspectConfigDestroyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RfidTagIndexController_DestroyRfidReturnInspectEntities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RfidReturnInspectEntitiesDestroyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RfidTagIndexControllerServer).DestroyRfidReturnInspectEntities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RfidTagIndexController_DestroyRfidReturnInspectEntities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RfidTagIndexControllerServer).DestroyRfidReturnInspectEntities(ctx, req.(*RfidReturnInspectEntitiesDestroyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RfidTagIndexController_InspectConfigOptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectConfigOptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RfidTagIndexControllerServer).InspectConfigOptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RfidTagIndexController_InspectConfigOptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RfidTagIndexControllerServer).InspectConfigOptions(ctx, req.(*InspectConfigOptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RfidTagIndexController_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RfidTagIndexListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RfidTagIndexControllerServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RfidTagIndexController_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RfidTagIndexControllerServer).List(ctx, req.(*RfidTagIndexListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RfidTagIndexController_ListRfidReasonEntities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RfidReasonEntitiesListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RfidTagIndexControllerServer).ListRfidReasonEntities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RfidTagIndexController_ListRfidReasonEntities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RfidTagIndexControllerServer).ListRfidReasonEntities(ctx, req.(*RfidReasonEntitiesListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RfidTagIndexController_ListRfidReturnInspectAgg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RfidReturnInspectAggListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RfidTagIndexControllerServer).ListRfidReturnInspectAgg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RfidTagIndexController_ListRfidReturnInspectAgg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RfidTagIndexControllerServer).ListRfidReturnInspectAgg(ctx, req.(*RfidReturnInspectAggListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RfidTagIndexController_ListRfidReturnInspectConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RfidReturnInspectConfigListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RfidTagIndexControllerServer).ListRfidReturnInspectConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RfidTagIndexController_ListRfidReturnInspectConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RfidTagIndexControllerServer).ListRfidReturnInspectConfig(ctx, req.(*RfidReturnInspectConfigListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RfidTagIndexController_ListRfidReturnInspectEntities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RfidReturnInspectEntitiesListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RfidTagIndexControllerServer).ListRfidReturnInspectEntities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RfidTagIndexController_ListRfidReturnInspectEntities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RfidTagIndexControllerServer).ListRfidReturnInspectEntities(ctx, req.(*RfidReturnInspectEntitiesListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RfidTagIndexController_PartialUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RfidTagIndexPartialUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RfidTagIndexControllerServer).PartialUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RfidTagIndexController_PartialUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RfidTagIndexControllerServer).PartialUpdate(ctx, req.(*RfidTagIndexPartialUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RfidTagIndexController_Retrieve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RfidTagIndexRetrieveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RfidTagIndexControllerServer).Retrieve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RfidTagIndexController_Retrieve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RfidTagIndexControllerServer).Retrieve(ctx, req.(*RfidTagIndexRetrieveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RfidTagIndexController_RetrieveReturnInspectAgg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveReturnInspectAggRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RfidTagIndexControllerServer).RetrieveReturnInspectAgg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RfidTagIndexController_RetrieveReturnInspectAgg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RfidTagIndexControllerServer).RetrieveReturnInspectAgg(ctx, req.(*RetrieveReturnInspectAggRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RfidTagIndexController_RetrieveRfidReasonEntities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RfidReasonEntitiesRetrieveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RfidTagIndexControllerServer).RetrieveRfidReasonEntities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RfidTagIndexController_RetrieveRfidReasonEntities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RfidTagIndexControllerServer).RetrieveRfidReasonEntities(ctx, req.(*RfidReasonEntitiesRetrieveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RfidTagIndexController_RetrieveRfidReturnInspectConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RfidReturnInspectConfigRetrieveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RfidTagIndexControllerServer).RetrieveRfidReturnInspectConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RfidTagIndexController_RetrieveRfidReturnInspectConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RfidTagIndexControllerServer).RetrieveRfidReturnInspectConfig(ctx, req.(*RfidReturnInspectConfigRetrieveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RfidTagIndexController_RetrieveRfidReturnInspectEntities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RfidReturnInspectEntitiesRetrieveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RfidTagIndexControllerServer).RetrieveRfidReturnInspectEntities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RfidTagIndexController_RetrieveRfidReturnInspectEntities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RfidTagIndexControllerServer).RetrieveRfidReturnInspectEntities(ctx, req.(*RfidReturnInspectEntitiesRetrieveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RfidTagIndexController_RfidEpcSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EpcSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RfidTagIndexControllerServer).RfidEpcSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RfidTagIndexController_RfidEpcSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RfidTagIndexControllerServer).RfidEpcSync(ctx, req.(*EpcSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RfidTagIndexController_RfidReturnInspectAggSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RfidReturnInspectAggSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RfidTagIndexControllerServer).RfidReturnInspectAggSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RfidTagIndexController_RfidReturnInspectAggSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RfidTagIndexControllerServer).RfidReturnInspectAggSync(ctx, req.(*RfidReturnInspectAggSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RfidTagIndexController_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RfidTagIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RfidTagIndexControllerServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RfidTagIndexController_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RfidTagIndexControllerServer).Update(ctx, req.(*RfidTagIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RfidTagIndexController_UpdateRfidReasonEntities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RfidReasonEntitiesUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RfidTagIndexControllerServer).UpdateRfidReasonEntities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RfidTagIndexController_UpdateRfidReasonEntities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RfidTagIndexControllerServer).UpdateRfidReasonEntities(ctx, req.(*RfidReasonEntitiesUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RfidTagIndexController_UpdateRfidReturnInspectConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RfidReturnInspectConfigUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RfidTagIndexControllerServer).UpdateRfidReturnInspectConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RfidTagIndexController_UpdateRfidReturnInspectConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RfidTagIndexControllerServer).UpdateRfidReturnInspectConfig(ctx, req.(*RfidReturnInspectConfigUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RfidTagIndexController_UpdateRfidReturnInspectEntities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RfidReturnInspectEntitiesUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RfidTagIndexControllerServer).UpdateRfidReturnInspectEntities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RfidTagIndexController_UpdateRfidReturnInspectEntities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RfidTagIndexControllerServer).UpdateRfidReturnInspectEntities(ctx, req.(*RfidReturnInspectEntitiesUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RfidTagIndexController_ServiceDesc is the grpc.ServiceDesc for RfidTagIndexController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RfidTagIndexController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rfid_tag_manage.tag_service.RfidTagIndexController",
	HandlerType: (*RfidTagIndexControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BulkPushReturnInspectAgg",
			Handler:    _RfidTagIndexController_BulkPushReturnInspectAgg_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _RfidTagIndexController_Create_Handler,
		},
		{
			MethodName: "CreateRfidReasonEntities",
			Handler:    _RfidTagIndexController_CreateRfidReasonEntities_Handler,
		},
		{
			MethodName: "CreateRfidReturnInspectConfig",
			Handler:    _RfidTagIndexController_CreateRfidReturnInspectConfig_Handler,
		},
		{
			MethodName: "CreateRfidReturnInspectEntities",
			Handler:    _RfidTagIndexController_CreateRfidReturnInspectEntities_Handler,
		},
		{
			MethodName: "Destroy",
			Handler:    _RfidTagIndexController_Destroy_Handler,
		},
		{
			MethodName: "DestroyReturnInspectAgg",
			Handler:    _RfidTagIndexController_DestroyReturnInspectAgg_Handler,
		},
		{
			MethodName: "DestroyRfidReasonEntities",
			Handler:    _RfidTagIndexController_DestroyRfidReasonEntities_Handler,
		},
		{
			MethodName: "DestroyRfidReturnInspectConfig",
			Handler:    _RfidTagIndexController_DestroyRfidReturnInspectConfig_Handler,
		},
		{
			MethodName: "DestroyRfidReturnInspectEntities",
			Handler:    _RfidTagIndexController_DestroyRfidReturnInspectEntities_Handler,
		},
		{
			MethodName: "InspectConfigOptions",
			Handler:    _RfidTagIndexController_InspectConfigOptions_Handler,
		},
		{
			MethodName: "List",
			Handler:    _RfidTagIndexController_List_Handler,
		},
		{
			MethodName: "ListRfidReasonEntities",
			Handler:    _RfidTagIndexController_ListRfidReasonEntities_Handler,
		},
		{
			MethodName: "ListRfidReturnInspectAgg",
			Handler:    _RfidTagIndexController_ListRfidReturnInspectAgg_Handler,
		},
		{
			MethodName: "ListRfidReturnInspectConfig",
			Handler:    _RfidTagIndexController_ListRfidReturnInspectConfig_Handler,
		},
		{
			MethodName: "ListRfidReturnInspectEntities",
			Handler:    _RfidTagIndexController_ListRfidReturnInspectEntities_Handler,
		},
		{
			MethodName: "PartialUpdate",
			Handler:    _RfidTagIndexController_PartialUpdate_Handler,
		},
		{
			MethodName: "Retrieve",
			Handler:    _RfidTagIndexController_Retrieve_Handler,
		},
		{
			MethodName: "RetrieveReturnInspectAgg",
			Handler:    _RfidTagIndexController_RetrieveReturnInspectAgg_Handler,
		},
		{
			MethodName: "RetrieveRfidReasonEntities",
			Handler:    _RfidTagIndexController_RetrieveRfidReasonEntities_Handler,
		},
		{
			MethodName: "RetrieveRfidReturnInspectConfig",
			Handler:    _RfidTagIndexController_RetrieveRfidReturnInspectConfig_Handler,
		},
		{
			MethodName: "RetrieveRfidReturnInspectEntities",
			Handler:    _RfidTagIndexController_RetrieveRfidReturnInspectEntities_Handler,
		},
		{
			MethodName: "RfidEpcSync",
			Handler:    _RfidTagIndexController_RfidEpcSync_Handler,
		},
		{
			MethodName: "RfidReturnInspectAggSync",
			Handler:    _RfidTagIndexController_RfidReturnInspectAggSync_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _RfidTagIndexController_Update_Handler,
		},
		{
			MethodName: "UpdateRfidReasonEntities",
			Handler:    _RfidTagIndexController_UpdateRfidReasonEntities_Handler,
		},
		{
			MethodName: "UpdateRfidReturnInspectConfig",
			Handler:    _RfidTagIndexController_UpdateRfidReturnInspectConfig_Handler,
		},
		{
			MethodName: "UpdateRfidReturnInspectEntities",
			Handler:    _RfidTagIndexController_UpdateRfidReturnInspectEntities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tag_manager.proto",
}
